name: talksy
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  build_runner: ^2.4.13
  carousel_slider: ^5.0.0
  cupertino_icons: ^1.0.8
  easy_localization: ^3.0.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_native_splash: ^2.4.2
  flutter_screenutil: ^5.9.3
  flutter_svg: ^2.0.13
  google_fonts: ^6.2.1
  http: ^1.2.2
  image_picker: ^1.1.2
  injectable: ^1.5.3
  injectable_generator: ^1.5.3
  permission_handler: ^11.3.1
  pin_code_fields: ^8.0.1
  curved_navigation_bar:
dev_dependencies:
  flutter_test:
    sdk: flutter

# Move easy_localization config inside flutter section
flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/translations/
    - assets/images/profile/
    - assets/images/onboarding/

# Move flutter_native_splash to top level
flutter_native_splash:
  color: "#ffffff"
  background_image: "assets/images/Splash Screen.png"

# Move easy_localization config to top level
# easy_localization:
#   path: assets/translation/  # Changed from assets_path to path
#   output_dir: lib/domain/generated/  # Changed from output_path to output_dir
